version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_agendaapi
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: agendaapi_db
      POSTGRES_USER: agenda_user
      POSTGRES_PASSWORD: agenda_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: